const  INITIALIZE_GAME = 'INITIALIZE_GAME';
const SELECT_PIECE = 'SELECT_PIECE';
const MOVE_PIECE = 'MOVE_PIECE'; 
const CALCULATE_ALLOWED_SQUARE = 'CALCULATE_ALLOWED_SQUARE'; 
const SYNC_OPPONENT_MOVE = 'SYNC_OPPONENT_MOVE';

export {
    INITIALIZE_GAME,
    SELECT_PIECE,
    MOVE_PIECE,
    CALCULATE_ALLOWED_SQUARE,
    SYNC_OPPONENT_MOVE
};
